feat: Update the SHA for comment plan results.

diff --git a/.github/workflows/reusable-terragrunt-plan-only.yml b/.github/workflows/reusable-terragrunt-plan-only.yml
--- a/.github/workflows/reusable-terragrunt-plan-only.yml
+++ b/.github/workflows/reusable-terragrunt-plan-only.yml
@@ -276,7 +276,12 @@ jobs:
           INPUT_PRE_EXEC_0: |
             ${{ inputs.before_plan_commands }}
           INPUT_POST_EXEC_0: |
-            terraform show -json plan.tfplan > plan.json
+            PLAN_PATH=$(find . -name plan.tfplan | head -n 1)
+            if [ -z "$PLAN_PATH" ]; then
+              echo "Error: plan.tfplan not found"
+              exit 1
+            fi
+            terraform show -json "$PLAN_PATH" > plan.json
             ${{ inputs.after_plan_commands }}
           TF_VAR_organization_tag: ${{ steps.set-tags-aws.outputs.TF_VAR_organization_tag }}
           TF_VAR_repository_tag: ${{ steps.set-tags-aws.outputs.TF_VAR_repository_tag }}
